version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: chambua-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chambua-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/chambua_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8082/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chambua-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
