server:
  port: 8082

spring:
  application:
    name: chambua-vismart
  profiles:
    default: dev
  jackson:
    time-zone: Africa/Nairobi
  datasource:
    url: jdbc:mysql://localhost:3306/chambua?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Nairobi&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc.time_zone: Africa/Nairobi
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true

# Profiles
---
spring:
  config:
    activate:
      on-profile: dev
  jackson:
    time-zone: Africa/Nairobi
  datasource:
    url: jdbc:mysql://localhost:3306/chambua?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Nairobi&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: Africa/Nairobi
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: test
  jackson:
    time-zone: Africa/Nairobi
  datasource:
    url: jdbc:mysql://localhost:3306/chambua_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Nairobi&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: Africa/Nairobi
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: prod
  jackson:
    time-zone: Africa/Nairobi
  datasource:
    url: jdbc:mysql://localhost:3306/chambua_prod?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Nairobi&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: Africa/Nairobi
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true
