name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # For project pages: https://<user>.github.io/<repo>/ -> "/<repo>/"
      # For user/organization pages repo named <user>.github.io -> "/"
      BASE_HREF: ${{ github.event.repository.name == (github.repository_owner + '.github.io') && '/' || format('/{0}/', github.event.repository.name) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'Chambuavismart/Chambuavismart/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: Chambuavismart/Chambuavismart/frontend
        run: npm ci

      - name: Build Angular app
        working-directory: Chambuavismart/Chambuavismart/frontend
        run: |
          echo "Using base href: $BASE_HREF"
          npx ng build --configuration production --base-href "$BASE_HREF"

      - name: Prepare Pages artifact (SPA routing)
        working-directory: Chambuavismart/Chambuavismart/frontend/dist/app
        run: |
          cp index.html 404.html
          touch .nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Chambuavismart/Chambuavismart/frontend/dist/app

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
