name: Publish frontend to gh-pages (branch-based Pages)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      # For project pages: https://<user>.github.io/<repo>/ -> "/<repo>/"
      # For user/organization pages repo named <user>.github.io -> "/"
      BASE_HREF: ${{ github.event.repository.name == format('{0}.github.io', github.repository_owner) && '/' || format('/{0}/', github.event.repository.name) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'Chambuavismart/Chambuavismart/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: Chambuavismart/Chambuavismart/frontend
        run: npm ci

      - name: Build Angular app
        working-directory: Chambuavismart/Chambuavismart/frontend
        run: |
          echo "Using base href: $BASE_HREF"
          npx ng build --configuration production --base-href "$BASE_HREF"

      - name: Prepare SPA routing files
        working-directory: Chambuavismart/Chambuavismart/frontend/dist/app
        run: |
          cp index.html 404.html
          touch .nojekyll

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: Chambuavismart/Chambuavismart/frontend/dist/app
          force_orphan: true
          commit_message: "chore(pages): publish static site from CI (${GITHUB_SHA})"